apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
        - name: probe
          image: {{ .Values.image | quote }}
          imagePullPolicy: IfNotPresent
          env:
            - name: FLEET_MANAGER_ENDPOINT
              value: {{ .Values.fleetManagerEndpoint | quote }}
            - name: AUTH_TYPE
              value: {{ .Values.authType | quote }}
            {{- if eq .Values.authType "RHSSO" }}
            - name: RHSSO_SERVICE_ACCOUNT_CLIENT_ID
              value: {{ .Values.redHatSSO.clientId | quote  }}
            - name: RHSSO_SERVICE_ACCOUNT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: rhacs-probe-rhsso-client-secret
                  key: CLIENT_SECRET
            - name: RHSSO_ENDPOINT
              value: {{ .Values.redHatSSO.endpoint | quote  }}
            - name: RHSSO_REALM
              value: {{ .Values.redHatSSO.realm | quote  }}
            {{- else if eq .Values.authType "OCM" }}
            - name: OCM_USERNAME
              value: {{ .Values.ocm.username | quote  }}
            - name: OCM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: rhacs-probe-ocm-token
                  key: TOKEN
            {{- end }}
          ports:
            - name: monitoring
              containerPort: 7070
      terminationGracePeriodSeconds: 300
