apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/observability-operator.rhacs-observability: ''
  name: observability-operator
  namespace: {{ include "observability.namespace" . }}
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: observability-operator
  source: observability-operator-manifests
  sourceNamespace: {{ include "observability.namespace" . }}
  startingCSV: observability-operator.{{ .Values.observabilityOperatorVersion }}
