---
#- A list of clusters for fleet manager
#- The `cluster_id` field can not be empty
#- All clusters in fleet manager DB already but are missing in the list will be marked as
#  'deprovisioning' and will later be deleted.
#- This list is ordered, any new cluster should be appended at the end.
clusters:
 - name: default/api-acs-dp-01-ce55-p1-openshiftapps-com:6443/acsms-admin
   # With OCM logged, given the cluster name get cluster id: `ocm get /api/clusters_mgmt/v1/clusters --parameter search="name = 'acs-dp-01'" | jq -r .items[].id`
   cluster_id: 1smhq7nc0ncfv2jbjgf48q7e6qb943ou
   cloud_provider: aws
   region: us-east-1
   schedulable: true
   status: ready
   central_instance_limit: 10
   provider_type: standalone
   supported_instance_type: "eval,standard"
   cluster_dns: acs-dp-01.ce55.p1.openshiftapps.com
   available_central_operator_versions:
    - version: "3.70.0"
      ready: true
      central_versions:
       - version: "3.70.0"
