apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: fleetshard-sync
  name: fleetshard-sync
  namespace: "$ACSMS_NAMESPACE"
spec:
  replicas: 1
  selector:
    matchLabels:
      application: fleetshard-sync
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        application: fleetshard-sync
    spec:
      containers:
        - command:
          - "sh"
          - "-c"
          - "$FLEETSHARD_SYNC_CONTAINER_COMMAND"
          env:
            - name: KUBECONFIG
              value: "/secrets/kubeconfig"
            - name: CLUSTER_ID
              value: "1234567890abcdef1234567890abcdef" # pragma: allowlist secret
            - name: FLEET_MANAGER_ENDPOINT
              value: http://fleet-manager:8000
            - name: RHSSO_SERVICE_ACCOUNT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: fleetshard-sync
                  key: "rhsso-service-account-client-id"
                  optional: false
            - name: RHSSO_SERVICE_ACCOUNT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: fleetshard-sync
                  key: "rhsso-service-account-client-secret"
                  optional: false
            - name: RUNTIME_POLL_PERIOD
              value: 10s
            - name: MANAGED_DB_ENABLED
              value: "$MANAGED_DB_ENABLED"
            - name: MANAGED_DB_SECURITY_GROUP
              value: "$MANAGED_DB_SECURITY_GROUP"
            - name: MANAGED_DB_SUBNET_GROUP
              value: "$MANAGED_DB_SUBNET_GROUP"
            - name: MANAGED_DB_PERFORMANCE_INSIGHTS
              value: "$MANAGED_DB_PERFORMANCE_INSIGHTS"
            - name: AWS_ROLE_ARN
              valueFrom:
                secretKeyRef:
                  name: fleetshard-sync
                  key: "aws-role-arn"

          image: "${FLEET_MANAGER_IMAGE}"
          imagePullPolicy: IfNotPresent
          name: fleetshard-sync
          resources: $FLEETSHARD_SYNC_RESOURCES
          volumeMounts:
            - mountPath: /secrets
              name: secrets
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: secrets
          secret:
            secretName: fleetshard-sync # pragma: allowlist secret
            optional: false
        - name: config
          configMap:
            name: config
